# The 'default' target is what gets run when you execute 'make' without specifying a target.
# Here, it's set to 'giftcardreader', which means 'make' will behave the same as 'make giftcardreader'.
default: giftcardreader

# The 'giftcardreader' target depends on 'giftcardreader.c' and 'giftcard.h'.
# This means that if either of these files changes, the 'giftcardreader' target needs to be rebuilt.
# The command 'gcc -g -o giftcardreader giftcardreader.c' compiles 'giftcardreader.c' into an executable named 'giftcardreader'.
# '-g' adds debugging information to the executable, which is useful for debugging.
# '-o giftcardreader' specifies the output file name for the compiled executable.
giftcardreader: giftcardreader.c giftcard.h
	gcc -g -o giftcardreader giftcardreader.c

# The 'asan' target is similar to 'giftcardreader' but includes the AddressSanitizer via '-fsanitize=address'.
# This sanitizer is a tool that finds memory errors in C/C++ programs.
# Like 'giftcardreader', it depends on 'giftcardreader.c' and 'giftcard.h'.
# It also compiles 'giftcardreader.c' into an executable named 'giftcardreader', but with additional memory error detection.
asan: giftcardreader.c giftcard.h
	gcc -fsanitize=address -g -o giftcardreader giftcardreader.c

# The 'test' target depends on the 'giftcardreader' target.
# It runs a script named 'runtests.sh' after building 'giftcardreader'.
# This is typically used to execute a suite of tests on the compiled program.
# './runtests.sh' means it will execute the 'runtests.sh' script located in the current directory.
test: giftcardreader
	./runtests.sh

# '.PHONY' is a special built-in target that helps to avoid conflicts with files of the same name and to improve performance.
# It tells make that 'clean' is not a file to be built, but a command to be executed.
# Targets listed in '.PHONY' are always executed even if a file with the same name exists.
.PHONY: clean

# The 'clean' target is typically used to delete all files generated by the build process.
# 'rm -f *.o giftcardreader' removes all '.o' files (object files) and the 'giftcardreader' executable.
# '-f' forces the deletion without prompting for confirmation.
clean:
	rm -f *.o giftcardreader
